CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    role TEXT NOT NULL
);

CREATE TABLE clients (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    legal_entity_name TEXT NOT NULL,
    registered_address TEXT NOT NULL,
    billing_address TEXT NULL,
    billing_same_as_registered BOOLEAN DEFAULT TRUE,
    mode_of_payment TEXT NOT NULL,
    gst_number TEXT NOT NULL,
    billing_currency TEXT NOT NULL,
    primary_contact_name TEXT NOT NULL,
    primary_contact_designation TEXT NULL,
    primary_contact_phone TEXT NOT NULL,
    primary_contact_email TEXT NOT NULL
);

CREATE TABLE projects (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_code TEXT NOT NULL UNIQUE,
    client_id INTEGER NOT NULL REFERENCES clients(id),
    created_by INTEGER NOT NULL REFERENCES users(id),
    name TEXT NOT NULL,
    active_version_id INTEGER NULL
);

CREATE TABLE project_versions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id INTEGER NOT NULL REFERENCES projects(id),
    version_number INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'draft',
    project_name TEXT NOT NULL,
    project_start_date DATE NOT NULL,
    project_end_date DATE NOT NULL,
    business_unit TEXT NOT NULL,
    reviewer_id INTEGER NOT NULL REFERENCES users(id),
    creator_id INTEGER NOT NULL REFERENCES users(id),
    submitted_at TIMESTAMP NULL,
    approved_at TIMESTAMP NULL,
    rejected_at TIMESTAMP NULL,
    rejection_comment TEXT NULL,
    is_active BOOLEAN DEFAULT FALSE
);

ALTER TABLE projects
    ADD CONSTRAINT projects_active_version_id_fk
    FOREIGN KEY (active_version_id) REFERENCES project_versions(id);

CREATE TABLE contract_documents (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_version_id INTEGER NOT NULL REFERENCES project_versions(id),
    document_type TEXT NOT NULL,
    valid_from DATE NOT NULL,
    valid_till DATE NOT NULL,
    s3_key TEXT NOT NULL,
    filename TEXT NOT NULL,
    uploaded_at TIMESTAMP NOT NULL
);

CREATE TABLE rate_cards (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    rate_per_hour TEXT NOT NULL,
    currency TEXT NOT NULL
);

CREATE TABLE job_categories (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_version_id INTEGER NOT NULL REFERENCES project_versions(id),
    name TEXT NOT NULL,
    rate_card_id INTEGER NOT NULL REFERENCES rate_cards(id)
);

CREATE TABLE approval_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_version_id INTEGER NOT NULL REFERENCES project_versions(id),
    action TEXT NOT NULL,
    actor_id INTEGER NOT NULL REFERENCES users(id),
    comment TEXT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE audit_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    action TEXT NOT NULL,
    actor_id INTEGER NOT NULL,
    data JSONB NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX users_id_idx ON users(id);
CREATE INDEX clients_id_idx ON clients(id);
